{% set name = "JTango" %}
{% set version = "9.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/JTango/-/archive/{{ version }}/JTango-{{ version }}.tar.gz
  sha256: 1da51146d14dd5f7943bc278969684e5d8a2f224f4abeb737ead8e6519012ddb

build:
  number: 0

requirements:
  build:
    - openjdk 8
    - maven
  run:
    - openjdk >=8

test:
  commands:
    - test -f ${PREFIX}/share/java/JTango.jar                      # [unix]
    - test -f ${PREFIX}/share/java/JTango-${PKG_VERSION}.jar       # [unix]
    - test -f ${PREFIX}/share/tango/logback.xml                    # [unix]
    - test -f ${PREFIX}/share/tango/logback-server.xml             # [unix]
    - if not exist %PREFIX%\share\java\JTango.jar exit 1           # [win]
    - if not exist %PREFIX%\share\tango\logback.xml exit 1         # [win]
    - if not exist %PREFIX%\share\tango\logback-server.xml exit 1  # [win]

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html

  summary: TANGO kernel Java implementation.
  description: |
    TANGO kernel Java implementation. Compatible with Java 8 and onwards.
    Tango-Controls is a software toolkit for building control systems.
  doc_url: https://jtango.readthedocs.io/
  dev_url: https://gitlab.com/tango-controls/JTango

extra:
  recipe-maintainers:
    - beenje
