{% set version = "9.7.2" %}

package:
  name: jtango-split
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/JTango/-/archive/{{ version }}/JTango-{{ version }}.tar.gz
  sha256: 6bbbb17a8f858a698fdbe0265973f34c344b2f0e920bddfeefcfc987bbe33391

build:
  number: 1

requirements:
  build:
    - openjdk 11
    - maven
  run:
    - openjdk >=11

outputs:
  - name: jtango-logback
    script: install-logback.sh  # [unix]
    script: install-logback.bat  # [win]
    test:
      commands:
        - test -f ${PREFIX}/share/tango/logback.xml                    # [unix]
        - test -f ${PREFIX}/share/tango/logback-server.xml             # [unix]
        - if not exist %PREFIX%\share\tango\logback.xml exit 1         # [win]
        - if not exist %PREFIX%\share\tango\logback-server.xml exit 1  # [win]
        # Test absence of jar file
        - test ! -f ${PREFIX}/share/java/JTango.jar                    # [unix]
        - if exist %PREFIX%\share\java\JTango.jar exit 1               # [win]

  - name: jtango
    script: install-jar.sh   # [unix]
    script: install-jar.bat  # [win]
    requirements:
      run:
        - {{ pin_subpackage("jtango-logback", exact=True) }}
        - openjdk >=8
    test:
      commands:
        - test -f ${PREFIX}/share/java/JTango.jar                      # [unix]
        - test -f ${PREFIX}/share/java/JTango-${PKG_VERSION}.jar       # [unix]
        - if not exist %PREFIX%\share\java\JTango.jar exit 1           # [win]

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html

  summary: TANGO kernel Java implementation.
  description: |
    TANGO kernel Java implementation. Compatible with Java 8 and onwards.
    Tango-Controls is a software toolkit for building control systems.
  doc_url: https://jtango.readthedocs.io/
  dev_url: https://gitlab.com/tango-controls/JTango

extra:
  feedstock-name: jtango
  recipe-maintainers:
    - beenje
